#ifndef UMDP_PROTOCOL_H
#define UMDP_PROTOCOL_H

#define UMDP_GENL_NAME "UMDP"
#define UMDP_GENL_VERSION 1
#define UMDP_GENL_INTERRUPT_MULTICAST_NAME "interrupt"

enum {
    UMDP_CMD_UNSPEC __attribute__((unused)) = 0,
    UMDP_CMD_ECHO = 1,
    UMDP_CMD_CONNECT = 2,
    UMDP_CMD_DEVIO_READ = 3,
    UMDP_CMD_DEVIO_WRITE = 4,
    UMDP_CMD_DEVIO_REQUEST = 5,
    UMDP_CMD_DEVIO_RELEASE = 6,
    UMDP_CMD_INTERRUPT_NOTIFICATION = 7,
    UMDP_CMD_INTERRUPT_SUBSCRIBE = 8,
    UMDP_CMD_INTERRUPT_UNSUBSCRIBE = 9,
    __UMDP_CMD_MAX,
};
#define UMDP_CMD_MAX (__UMDP_CMD_MAX - 1)

enum {
    UMDP_ATTR_ECHO_UNSPEC __attribute__((unused)) = 0,
    UMDP_ATTR_ECHO_MSG = 1,
    __UMDP_ATTR_ECHO_MAX,
};
#define UMDP_ATTR_ECHO_MAX (__UMDP_ATTR_ECHO_MAX - 1)

enum {
    UMDP_ATTR_CONNECT_UNSPEC __attribute__((unused)) = 0,
    UMDP_ATTR_CONNECT_PID = 1,
    UMDP_ATTR_CONNECT_REPLY = 2,
    __UMDP_ATTR_CONNECT_MAX,
};
#define UMDP_ATTR_CONNECT_MAX (__UMDP_ATTR_CONNECT_MAX - 1)

enum {
    UMDP_ATTR_DEVIO_READ_UNSPEC __attribute__((unused)) = 0,
    UMDP_ATTR_DEVIO_READ_PORT = 1,
    UMDP_ATTR_DEVIO_READ_TYPE = 2,
    UMDP_ATTR_DEVIO_READ_REPLY_U8 = 3,
    UMDP_ATTR_DEVIO_READ_REPLY_U16 = 4,
    UMDP_ATTR_DEVIO_READ_REPLY_U32 = 5,
    __UMDP_ATTR_DEVIO_READ_MAX,
};
#define UMDP_ATTR_DEVIO_READ_MAX (__UMDP_ATTR_DEVIO_READ_MAX - 1)

enum {
    UMDP_ATTR_DEVIO_WRITE_UNSPEC __attribute__((unused)) = 0,
    UMDP_ATTR_DEVIO_WRITE_PORT = 1,
    UMDP_ATTR_DEVIO_WRITE_VALUE_U8 = 2,
    UMDP_ATTR_DEVIO_WRITE_VALUE_U16 = 3,
    UMDP_ATTR_DEVIO_WRITE_VALUE_U32 = 4,
    __UMDP_ATTR_DEVIO_WRITE_MAX,
};
#define UMDP_ATTR_DEVIO_WRITE_MAX (__UMDP_ATTR_DEVIO_WRITE_MAX - 1)

enum {
    UMDP_ATTR_DEVIO_REQUEST_UNSPEC __attribute__((unused)) = 0,
    UMDP_ATTR_DEVIO_REQUEST_START = 1,
    UMDP_ATTR_DEVIO_REQUEST_SIZE = 2,
    __UMDP_ATTR_DEVIO_REQUEST_MAX,
};
#define UMDP_ATTR_DEVIO_REQUEST_MAX (__UMDP_ATTR_DEVIO_REQUEST_MAX - 1)

enum {
    UMDP_ATTR_INTERRUPT_UNSPEC __attribute__((unused)) = 0,
    UMDP_ATTR_INTERRUPT_IRQ = 1,
    __UMDP_ATTR_INTERRUPT_MAX,
};
#define UMDP_ATTR_INTERRUPT_MAX (__UMDP_ATTR_INTERRUPT_MAX - 1)

#endif  // UMDP_PROTOCOL_H
